name = "gr-football-matchmaking"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[[durable_objects.bindings]]
name = "CLUB_ROOM"
class_name = "ClubRoom"

[[migrations]]
tag = "v1"
new_classes = ["ClubRoom"]
